version: "3.7"

volumes:
  db_data:

networks:
  default:
    driver: bridge

services:
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    container_name: db
    restart: unless-stopped
    networks:
      - default
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./db:/var/opt/mssql/data/backup
    environment:
      SA_PASSWORD: "HmzTest@123"
      ACCEPT_EULA: "Y"

  api:
    container_name: api
    restart: unless-stopped
    networks:
      - default
    build:
      context: ./api/HmzTest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db