@HmzTest_HostAddress = http://localhost:5285

POST {{HmzTest_HostAddress}}/api/users
Content-Type: application/json

{
  //CreateUserRequestDto
}

###

GET {{HmzTest_HostAddress}}/api/users

###

GET {{HmzTest_HostAddress}}/api/users/{id}

###

DELETE {{HmzTest_HostAddress}}/api/users/{id}

###

PATCH {{HmzTest_HostAddress}}/api/users/{id}
Content-Type: application/json

{
  //UpdateUserRequestDto
}

###
